<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Welcome, Pluton!</title>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Didact+Gothic&family=Dosis:wght@200&display=swap" rel="stylesheet">
    </head>
    <body>
        <div id="body">
            <div class="container">
                <div class="row">
                    <h1 id="title">Pluton<sup>php</sup></h1>
                </div>
                <div class="row">
                    <span id="label">MVC framework by <a href="https://github.com/sabuhiali/pluton">Sabuhi Alizada</a></span>
                </div>
            </div>
        </div>
        <style>
            *{
                padding: 0;
                margin: 0;
                box-sizing: border-box;
            }
            a{
                text-decoration: none;
            }
            body{
                font-family: 'Didact Gothic', sans-serif;
                font-size: 0.92em;
                line-height: 1.5;
            }
            #body{
                background: #fff;
                width: 100%;
                height: 100vh;
                display: flex;
                justify-content: center;
                align-items: center;
            }
            .container{
                width: 50%;
            }
            .row{
                width: 100%;
                padding: 8px;
                text-align: center;
            }
            #title{
                font-size: 80px;
                color: #404040;
            }
            #title sup{
                background: #4F5B93;
                background: linear-gradient(to top right, #4F5B93, #8892BF);
                color: #fff;
                font-size: 25px;
                padding: 8px;
                border-radius: 25px 0px 25px 0px;
            }
            #label{
                color: #404040;
            }
            #label a{
                color: #4F5B93;
            }
            #label a:hover{
                text-decoration: underline;
            }
        </style>
    </body>
</html>